[package]
name = "liftm/sam"
version = "0.0.0-1"
description = "Software Automatic Mouth"
license = "Abandonware"
repository = "https://github.com/jcaesar/wapm-pkg/"
homepage = "https://github.com/s-macke/SAM/"
readme = "README.md"

[[module]]
name = "sam"
source = "sam.wasm"
abi = "wasi"

[module.interfaces]
wasi = "0.1.0-unstable"

[[command]]
name = "sam"
module = "sam"
