[package]
name = "liftm/rq"
version = "1.0.3-alpha.0-1"
description = "A tool for doing record analysis and transformation"
license = "Apache-2.0"
repository = "https://github.com/jcaesar/wapm-pkg"
homepage = "https://github.com/dflemstr/rq"
readme = "README.md"

[[module]]
name = "rq"
source = "rq.wasm"
abi = "wasi"

[module.interfaces]
wasi = "0.1.0-unstable"

[[command]]
name = "rq"
module = "rq"
