[package]
name = "liftm/upx"
version = "4.0.2-1"
description = "A fast static site generator in a single binary with everything built-in. "
license = "GPL-2.0"
repository = "https://github.com/jcaesar/wapm-pkg/tree/HEAD/upx"
homepage = "https://upx.github.io/"
readme = "README.md"

[[module]]
name = "upx"
source = "upx"
abi = "wasi"

[module.interfaces]
wasi = "0.1.0-unstable"

[[command]]
name = "upx"
module = "upx"
