[package]
name = "liftm/metamath"
version = "0.198.20210807-4"
description = "A tiny language and checker for theorems and proofs in abstract mathematics"
license = "GPL-2"
repository = "https://github.com/jcaesar/wapm-pkg"
homepage = "http://us.metamath.org/mm.html"
readme = "README.md"

[[module]]
name = "metamath"
source = "metamath.wasm"
abi = "wasi"

[module.interfaces]
wasi = "0.1.0-unstable"

[[command]]
name = "metamath"
module = "metamath"
