[package]
name = "liftm/schermz"
version = "0.1.11-1"
description = "JSON Schema Generator"
license = "MIT"
repository = "https://github.com/jcaesar/wapm-pkg/tree/HEAD/schermz"
homepage = "https://github.com/trassmann/schermz"

[[module]]
name = "schermz"
source = "schermz"
abi = "wasi"

[module.interfaces]
wasi = "0.1.0-unstable"

[[command]]
name = "schermz"
module = "schermz"
